### ISSUE TITLE
Privacy Statement on all localized sites go to English site.

### ISSUE THREAD

**Issue by Melechuga** [MozillaFoundation/Advocacy#296]
![screen shot 2016-08-29 at 11 03 05 am](https://cloud.githubusercontent.com/assets/5815317/18061681/7b90c97e-6dd8-11e6-92ec-b7423ea5cc4e.png)

The link to the privacy statement goes to https://www.mozilla.org/en-US/privacy/websites/ for all localized sites; I think @ScottDowne fixed that last week, but it's reverting back now.

**Comment by Melechuga** [comment]
Also, the localized ones (French, German, and Polish at the moment) need a space in the text before the link.

**Comment by valianttry** [comment]
I am concerned because:
1. @ScottDowne already fixed the URLs once (can you confirm Scott?); and 
2. I already fixed the space issue once in all locales. 

I'm getting a bit frustrated that edits are reverting in Bablic. I'm not sure how to fix this problem, but i'm a bit tired of fixing the same things over and over again.

**Comment by valianttry** [comment]
I went through and fixed all the spaces in the privacy notice check box sentence, again.

**Comment by ScottDowne** [comment]
I didn't fix it, but I did mention in the bug that we just need to remove the en-US (I think it was a generic QA bug). That url should figure out the locale itself, so we have no reason to be specific.

It needs to be updated to https://www.mozilla.org/privacy/websites/

**Comment by ScottDowne** [comment]
I did have a change I made reverted as well. https://github.com/MozillaFoundation/Advocacy/issues/268

Maybe Fission has some sort of version control and updating/sync with NationBuilder?

So changes we make outside of their source might be reverted whenever they make a push?

**Comment by valianttry** [comment]
I fixed the URL in all locales in Bablic.
