### ISSUE TITLE
[Mobile] Country list in localized sites in English

### ISSUE THREAD

**Issue by Melechuga** [MozillaFoundation/Advocacy#306]
![img_9343](https://cloud.githubusercontent.com/assets/5815317/18065484/de11db32-6de8-11e6-9bd7-dd0120865c51.PNG)

In Spanish, French, German, and Polish the country lists are in English. This is Firefox on iOS and Safari on iOS.

**Comment by Melechuga** [comment]
FYI the actual lists are in English too.

**Comment by damiankay** [comment]
CC @jendc123

**Comment by jendc123** [comment]
@damiankay and @Melechuga we sent an email to Bablic last night and heard back this morning. We updated the code, but it's still a bit wonky. We've reached out again.

**Comment by jendc123** [comment]
@damiankay @Melechuga  - we have implemented a fix for this and it's working.

**Comment by damiankay** [comment]
Hi @jendc123 - I'm still seeing this error on Chrome / iPhone 5s. Both the "country" field name and the list of countries are in English. 
![img_9936](https://cloud.githubusercontent.com/assets/19785709/18137492/5c5674c4-6f5d-11e6-8186-372e171bf19f.PNG)

**Comment by jendc123** [comment]
Hi @damiankay - It looks like the Spanish translation isn't in Bablic? Is it happening with other languages?

**Comment by damiankay** [comment]
@jendc123 was just going to say that I successfully filled out the form in Polish. 

@valianttry can we re-enter the Spanish translations for country field and country list?

**Comment by ScottDowne** [comment]
Worked for me on Android and FF. Looks like all the countries are not in English, cept for English.

Although most of them are in all caps in French.

**Comment by damiankay** [comment]
Closing. All caps issues are also captured here: #303
